### ISSUE TITLE
UsAcquisitionObject wrong opacity

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#103]
Selecting USAcquisitionObject from the list will make slices opaque even if settings dialog shows different. Clicking in 3D window will reset the opacity to one from settings.

**Comment by nist-anka** [comment]
Only static slices loose their transparency.

**Comment by hgueziri** [comment]
I can't manage to reproduce the bug

**Comment by nist-anka** [comment]
Neither can I, we must have changed something that would fix it. Unfortunately, I don't know what. Closing.
