### ISSUE TITLE
Skewed 2D camera

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#2]
2D cameras sometimes loose alignment with plane and axes (see screenshot attached).
There may be different ways to reproduce the bug, but one consistent way is to manually modify the transform of the reference object and then press the Identity button in the transform tab of the ImageObject settings widget.
Views rely on the previous transform (as saved by the view) of the reference object to adjust the transform of the camera. One of the possible explanations for this bug is that this previous transform may not always be up to date and thus causes a readjustment of the camera transform that is incorrect.
Solving the bug might involve rethinking the mechanism to update the camera transform.
![screenshot from 2016-05-13 13-37-50](https://cloud.githubusercontent.com/assets/19712227/16848005/b34971c6-49c1-11e6-914c-1ff78d8dae23.png)

**Comment by nist-anka** [comment]
It happens also when you move registered reference object out of LandmarkRegistration

**Comment by drouin-simon** [comment]
Until we have a permanent fix, the reset views button should take care of realigning the views.

**Comment by nist-anka** [comment]
One of the reasons was the bug in vtkTransform::Identity(), I patched it in transformWidget.cpp

**Comment by nist-anka** [comment]
I do not see it happen anymore, proceeding as in the first description of the bug does not give skewed views.
