### ISSUE TITLE
Leak in USAcquisitionObject

### ISSUE THREAD

**Issue by drouin-simon** [IbisNeuronav/Ibis#208]
Vtk to Itk converter is created and never deleted here:

https://github.com/IbisNeuronav/Ibis/blob/27f0bf71449d98e3664a7bc8dadeedacff8ad4cc/IbisLib/usacquisitionobject.cpp#L852

and there

https://github.com/IbisNeuronav/Ibis/blob/27f0bf71449d98e3664a7bc8dadeedacff8ad4cc/IbisLib/usacquisitionobject.cpp#L906

**Comment by nist-anka** [comment]
Fixed using vtkSmartPointer
