### ISSUE TITLE
Transformations  wrong when loading successive scenes

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#221]
This may be related to #210
When you load scenes one after another without quitting ibis, transformations go wrong.
From ibis_data load Miguet_USAcquisition and then NonLinear_MR_to_MR.
![screenshot from 2019-02-04 09-17-05](https://user-images.githubusercontent.com/19712227/52214568-ed50a400-285f-11e9-82d9-9aaa37b44882.png)

**Comment by drouin-simon** [comment]
I don't think it is related to #210, which is probably nothing more than a missing callback in the transform widget to update gui when transform is changed internally.

**Comment by nist-anka** [comment]
Resolved
