### ISSUE TITLE
SceneManager::Clear() assert failure.

### ISSUE THREAD

**Issue by errollgarner** [IbisNeuronav/Ibis#246]
In SceneManager::Clear() the assert checking that the list of objects is empty after having removed all objects from the scene sometimes fails. To reproduce:
-Load a scene
-Import a camera calibration
-Load a scene

On this second scene load, it will crash due to the assert failure. After the RemoveAllSceneObjects() call, all Intrinsic views are still in the objects list. (Although, all Extrinsic views do indeed get removed.)

I am not sure if this is a bug in SceneManager or in the camera calibration import function. Perhaps these Intrinsic views aren't added as children of the scene root?

**Comment by nist-anka** [comment]
I don't have a crash, but I still see the axes made for the camera plugin, they are not removed when plugin id disabled.

**Comment by nist-anka** [comment]
Can be fixed after camera calibration is fixed.

**Comment by nist-anka** [comment]
Fixed in 40e0034c0ff7861b728399058da7b66c90fa231d
