### ISSUE TITLE
Unexpected behaviour for registration + GUI transform editing

### ISSUE THREAD

**Issue by hgueziri** [IbisNeuronav/Ibis#296]
If an object transform is modified from the GUI, the registration gives unexpected results (completely diverging). Can that be related to vtkLinearTransform that cannot be inverted? 
The code in the registration plugin does not directly use vtkLinearTransform though.

**Comment by nist-anka** [comment]
I have two images children of the same LandmarkRegistration, both images  with surfaces.
I translate one of images along  one of the axes, surfaces in 3D and images in 2D planes move in different directions
![Screenshot from 2019-12-04 12-26-53](https://user-images.githubusercontent.com/19712227/70165736-6ba0f100-1691-11ea-9315-3e9341d10424.png)

**Comment by nist-anka** [comment]
Fixed, but the matrix dialog is not updated if you modify transform outside of the dialog because it uses a copy of the matrix from the local transform.
