### ISSUE TITLE
Export of MINC files is not doing anything.

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#297]

**Comment by hgueziri** [comment]
The issue has nothing to do with file export. There is an inconsistency between vtkImageData and ItkImage information stored in ImageObject. Specifically, I am creating a new ImageObject with SetImage(vtkImageData *), but this function does not create an ItkImage version internally [see here](https://github.com/IbisNeuronav/Ibis/blob/961d385dc8b435b05c01283f9c491a4b440303b5/IbisLib/imageobject.cpp#L284). The other way around works though (using SetItkImage() does create a vtkImageData version internally). We need to check the consistency between the internal images.
