### ISSUE TITLE
Question: tracked tool timestamp

### ISSUE THREAD

**Issue by hgueziri** [IbisNeuronav/Ibis#309]
Is there a way to get the timestamp of a tracked tool?

The HardwareIGSIOPlugin contains information about timestamps in Tool but I am not sure if this is being saved anywhere in TrackedSceneObject, and if not should we add it?

**Comment by drouin-simon** [comment]
It is currently not in TrackedSceneObject, but should be added, it is a very useful information. We just have to push the data to the TrackedSceneObject at the same time as the transform and state and add a function like GetLastTimestamp() to TrackedSceneObject.
