### ISSUE TITLE
Long tool names not detected in IGSIO

### ISSUE THREAD

**Issue by hgueziri** [IbisNeuronav/Ibis#311]
If a DeviceName is too long (> 20 characters) it seems to be cropped. As a consequence the tool-transform association is not recognized. 
The problem seems to be in [line 285: GetDeviceName()](https://github.com/IbisNeuronav/Ibis/blob/b2e843244e0edd5a0f19b361f234e9754559c1f1/IbisHardwareIGSIO/ibishardwareIGSIO.cpp#L285) as deviceName given by igtlioDevice is truncated. I suspect a buffer size issue in IGSIO lib. Has anyone encountered this before? For now, I'm avoiding the issue by using shorter names.

**Comment by drouin-simon** [comment]
Yes. The problem is that the field for device name in OpenIGTLink header has only 20 characters long. There was a discussion at some point to include the untruncated name in the metadata, but I don't know if it was ever implemented.
