### ISSUE TITLE
Floating docks incorrectly positioned

### ISSUE THREAD

**Issue by errollgarner** [IbisNeuronav/Ibis#316]
The new way of displaying interaction dialogs through floating docks (#279) makes the top of the dialog inaccessible on Linux, making it hard to minimize or close it.

**Comment by hgueziri** [comment]
Looks fine for me (Ubuntu 18.04.2, Qt 5.9.5). What version of Qt are you using?

![Screenshot from 2019-12-05 11-44-04](https://user-images.githubusercontent.com/8172629/70255599-14645480-1755-11ea-90b4-42bff6f5427c.png)

**Comment by nist-anka** [comment]
Works for me also.

**Comment by errollgarner** [comment]
It seems to be related to having multiple displays connected. I have two displays of different resolutions. The dock always appear on the top left corner of the left screen, whichever screen Ibis is on. When the left one is the smallest of the two, the dock is too high (this was my initial setup). Although, if I switch the position of the two displays (to have the left one be the biggest), the dock is positioned properly.

**Comment by hgueziri** [comment]
You should be able to move the window with the mouse (by dragging) from the top title bar or by pressing the windows hotkey.
There is a way to specify the position of the dock in [MainWindow::ShowFloatingDock](https://github.com/IbisNeuronav/Ibis/blob/6b348aa32d9370b88979defe988efe4d9249b4cd/IbisLib/mainwindow.cpp#L881).

**Comment by hgueziri** [comment]
PR #317  should fix the issue

**Comment by errollgarner** [comment]
Indeed, it is now centered and fully visible.
