### ISSUE TITLE
Loading a scene removes model associated with tool in IGSIO Hardware

### ISSUE THREAD

**Issue by errollgarner** [IbisNeuronav/Ibis#327]
I have tested this with a pointer object, but I presume it would apply to other tools as well. 
Steps to reproduce:
-Launch an IGSIOHardware configuration where one of the tools has a ToolModelFile associated
-Load a scene
The model disappears.
If the hardware config is reloaded the model comes back. It thus looks like it might have something to do with how the ClearScene handles models perhaps.

**Comment by nist-anka** [comment]
It was fixed at some point, do you have the latest ibis?

**Comment by errollgarner** [comment]
I just tested on the master and you are correct, everything works as expect. I'll investigate on my side then. I'm sorry about that. I will close the issue.
