### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#337]
In view menu Fullscreen has to be changed to Full Screen

**Comment by nist-anka** [comment]
Help menu , change About plugins to About Plugins

**Comment by Ansh0611** [comment]
Can i take this?

**Comment by nist-anka** [comment]
Yes. I have corrected the 2 errors I found, but I have not closed the report yet as there maybe more spelling mistakes.

**Comment by nist-anka** [comment]
Sorry for being direct - who are you?
Anka
