### ISSUE TITLE
Removing C++ 11 directive breaks the build on Mac

### ISSUE THREAD

**Issue by drouin-simon** [IbisNeuronav/Ibis#362]
In commit: 5316e1b65539e8c2942ec9c87cde3ac0df54a8a4

The CMake directive for using C++ 11 breaks the build, at least on Mac. It creates a problem with the override keyword. Difficult to imagine this is not creating problems on other platforms as at least VTK requires C++ 11 now.

**Comment by nist-anka** [comment]
Vtk and itk require higher c++ than 11.

**Comment by nist-anka** [comment]
Before we merged this in, Josh has tested on Mac, Houssem and Renzo on
Windows and I on Ubuntu.

**Comment by drouin-simon** [comment]
The versions of vtk we currently use do not need higher than c++11. Actually, the current master branch of VTK is on C++ 11:
![image](https://user-images.githubusercontent.com/5595829/97352553-2f5a1e80-1869-11eb-8ee8-04633089a427.png)

**Comment by drouin-simon** [comment]
Default for master branch of ITK seems to be C++ 11 too:
![image](https://user-images.githubusercontent.com/5595829/97352858-937ce280-1869-11eb-8d4d-d006c8e51d84.png)

**Comment by drouin-simon** [comment]
If Ibis doesn't define a standard, ITK and VTK will fall back to the default c++ 11, so if Ibis itself doesn't pick a version, it will not get c++ 11, which means it will create problems with directives like override. I don't see how this can compile unless you are using a compiler that assume c++ >= 11

**Comment by nist-anka** [comment]
I have 17 on Ubuntu, Everything compiles and links beautifully.
I think the Windows c++ version  is also higher.
ITK compiles with the latest on the system, we removed c++11 because of
zillion compiler warnings telling, that we are using a compiler older than
our libraries were built with.Maybe there is another solution to get rid of
the warnings, you may always put back the flag.

**Comment by drouin-simon** [comment]
As shown in my comments above, ITK and VTK will use C++ 11 unless you explicitly specify a newer compiler in CMake, which we do not after the commit that removes the CMAKE_CXX_STANDARD directive. From the CMake code in the ITK repos, I don't see how ITK can use a c++ version higher than 11 without the user explicitly specifying it.

Which systems get the warnings? I don't get them on Mac. I use the latest compiler on Catalina:
Apple clang version 11.0.3 (clang-1103.0.32.62)

**Comment by drouin-simon** [comment]
Actually, there is a new version of the compiler (12). I'll give it a try. 

It is a good thing to specify in the CMake which version of the standard we are using. ITK and VTK do it.

**Comment by nist-anka** [comment]
I cannot say anything about MAC. The warnings are about one of the
libraries compiled in ITK - VNL.
Maybe other, I haven't seen,

**Comment by drouin-simon** [comment]
On Linux only?

**Comment by nist-anka** [comment]
Maybe Josh was using a newer version of C++ when he built?
He has not much experience, you are the MAC guy:-)

**Comment by nist-anka** [comment]
Yes, on Linux only, but it prevents us from seeing other warnings.

**Comment by nist-anka** [comment]
BTW,  I do not see the file  vtkCompilerChecks.cmake anywhere in my
vtk8.1.2 directory

**Comment by drouin-simon** [comment]
On Mac, default C++ standard for XCode 11 compiler is C++14, so it should work unless CMake is forcing Ibis to a lower version when not specified.

I'll do a fresh build with the updated compiler and we'll see. But I maintain it makes more sense to specify a C++ standard. There must be another way to fix the warnings.

the vtkCompilerChecks is in the master of VTK repos. Maybe it was added recently. The same code is in the main CMakeLists.txt in our version.

**Comment by nist-anka** [comment]
All CXX_STANDARD I can find

**Comment by nist-anka** [comment]
Let me know, if you want to revert the change. I agree, it is better to set
the standard.
I cannot find information about CMAKE_CXX_STANDARD_COMPUTED_DEFAULT
in cmake docs I find only
CMAKE_CXX_COMPILE_FEATURES
<https://www.systutorials.com/docs/linux/man/7-cmake3-variables/#lbLE>
CMAKE_CXX_EXTENSIONS
<https://www.systutorials.com/docs/linux/man/7-cmake3-variables/#lbLF>
CMAKE_CXX_STANDARD
<https://www.systutorials.com/docs/linux/man/7-cmake3-variables/#lbLG>
CMAKE_CXX_STANDARD_REQUIRED
<https://www.systutorials.com/docs/linux/man/7-cmake3-variables/#lbLH>
If we add *CXX_STANDARD_REQUIRED to ITK cmake, will it apply it to all
third modules?*

**Comment by drouin-simon** [comment]
We might need to pass CMAKE_CXX_STANDARD to external dependencies. But again, the default for VTK and ITK is c++11, so the warnings must be coming from somewhere else.

**Comment by drouin-simon** [comment]
In my current build, I have:

set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "98")

in the CMakeCXXCompiler.cmake of the build directory. Will see what I get with the updated compiler.

**Comment by nist-anka** [comment]
Reverted to C++11
