### ISSUE TITLE
SceneLoad crash when launching PlusServer externally

### ISSUE THREAD

**Issue by errollgarner** [IbisNeuronav/Ibis#391]
Ibis crashes when loading a scene (or loading a new hardware config) if the currently used hardware config had StartAuto=0. It seems that when ClearConfig is called, the list of tracked tools in the hardware module gets cleared, but the the ToolUI associated with the tool doesn't, causing a crash on Q_ASSERT( toolObject ) in ToolUI::UpdateUI(), as toolObject is now nullptr. I don't see why this only happens when StartAuto is set to 0. There doesn't seem to be anything relating how tools are added to the scene in the PlusServer launching code. Does anyone have an idea of why this happens?

**Comment by nist-anka** [comment]
I'm not sure how to reproduce it. I'm using webcam. I start ibis, my hardware config has Automatic Start 0, I click on Apply. That does not work, the cone shows, but the camera does not turn on, so I start Plus server from command line. That activates the camera. I click on load scene and the server disconnects, but no crash. 
Just message from server:
"Client disconnected - could not send IMAGE message to client (device name: Image_Image  Timestamp: 1612888201.775257)."
I go to hardware settings and again click on Apply and get the camera working.

I'll investigate why server disconnects.

What else should I check? How should I proceed?

**Comment by nist-anka** [comment]
Reproducing

1 start ibis
2 start PlusServer
3 load scene, crash

**Comment by nist-anka** [comment]
fixed
