### ISSUE TITLE
ERROR during build

### ISSUE THREAD

**Issue by Archie7777** [IbisNeuronav/Ibis#395]
Why did I get this error when I was building the project?

CMake Error in Ibis/CMakeLists.txt:
Evaluation file to be written multiple times with different content.  This
is generally caused by the content evaluating the configuration type,
language, or location of object files:

D:/IBIS/Ibis/Ibis/ibis_path

**Comment by nist-anka** [comment]
Please, give more details. What is your OS? Are you building the SuperBuild?

**Comment by hgueziri** [comment]
If you are building on Windows using Visual Studio, you need to specify only one build type at the time, change `CMAKE_CONFIGURATION_TYPES` variable to either `Release` or `Debug` and try again

**Comment by Archie7777** [comment]
Thank you, it realy is the matter of `CMAKE_CONFIGURATION_TYPES`.
