### ISSUE TITLE
Crash when starting GPURigidRegistration

### ISSUE THREAD

**Issue by nist-anka** [IbisNeuronav/Ibis#415]
On Ubuntu 2020, branch master
The crash happens sometimes, I cannot find what causes it.
I start ibis, load a scene with one acquisition and one reconstructed volume. I start GPURigidRegistration and it may crash.

The error:
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/anka/ibis_work/ibis/IbisPlugins/GPU_RigidRegistration/itkRegistrationOpenCL/itkGPUOrientationMatchingMatrixTransformationSparseMask.hxx:811:
OpenCL Error : CL_INVALID_HOST_PTR

in:

GPU_RigidRegistration::runRegistration            gpu_rigidregistration.cpp                                   299  (metric->Update())

Screenshot of the dialog when it works:
![Screenshot from 2021-05-03 11-34-29](https://user-images.githubusercontent.com/19712227/116897861-bebf0080-ac03-11eb-943f-bc5756092234.png)

May it be the mask that causes problems?

**Comment by hgueziri** [comment]
Hi,
Does that happen consistently each time you try your scene?
The issue seems to be related to memory allocation of the moving image on the GPU. What is the size of your image, maybe you don't have enough GPU memory? I'll investigate.

**Comment by nist-anka** [comment]
ceashonload.tar.xz
<https://drive.google.com/file/d/1iOUGRx7f5ZQ1zZ3QsQTXu7Ocmu-FQgIY/view?usp=drive_web>
This happens in a scene that I got from you. It does not happen every time.
I thought it may have something to do with mask?
screen shot shows my Nvidia params

**Comment by hgueziri** [comment]
I don't think the mask has to do with the bug. It's just the hxx file name. 
I am not able to reproduce the bug... also I am on Windows 10, OpenCL 2.2
- does that happen when you run registration several times on the same scene?
- what is your GPU memory size?

**Comment by nist-anka** [comment]
If it works the first time I run registration, then it will work on next
registration, I have not had a crash after few successful registrations.
Memory 8G.
Anka

**Comment by nist-anka** [comment]
The same thing happens on Windows 10 profwssional
![Screenshot 2021-05-24 08 56 20](https://user-images.githubusercontent.com/19712227/119351259-4b426900-bc6e-11eb-93f9-7a64aaabe947.png)

**Comment by nist-anka** [comment]
Fixed, but the matrix dialog is not updated if you modify transform iutside of the dialog because it uses a copy of the matrix from the local transform.
